[server]
# Increase max upload size to 1GB (1024 MB)
maxUploadSize = 1024

# Optional: Increase message size limit as well
maxMessageSize = 1024

[browser]
# Optional: Disable usage stats collection
gatherUsageStats = false